### ISSUE TITLE
Can't create Project from Giter8 Template

### ISSUE THREAD

**Issue by sujit-baniya** [coreyauger/typebus-service#1]
Hello,

I tried to create project from Giter8 Template but I'm getting `Auth Fail` error

https://www.dropbox.com/s/sf00dzthl0sqfdv/Screenshot%202019-09-30%2021.31.05.png?dl=0

**Comment by coreyauger** [comment]
Do you have ssh setup for github?

**Comment by sujit-baniya** [comment]
Yes! I did setup SSH for github... I managed to use HTTPS and use the Template. Thanks for the response. :)
